### ISSUE TITLE
Cannot add new camera device with 1.1.8 or 1.1.9

### ISSUE THREAD

**Issue by smeee-again** [Ghawken/IndigoPlugin-BlueIris#7]
I just noticed when I went to add a new camera that the generate camera devices did not exist.  I'm running Blue Iris 5 and have tried the 1.1.8 and 1.1.9 plugin.  I've attached a screenshot which shows that the add camera devices is not present.

<img width="512" alt="Screen Shot 2019-07-08 at 9 30 55 PM" src="https://user-images.githubusercontent.com/37485836/60855089-0c18e500-a1c8-11e9-80c3-a094bcdfc872.png">

**Comment by Ghawken** [comment]
Press the Login Generate Main Server Device - it then should appear?
If the server details are correct and the plugin can connect to the server - the log should show what is happending.

This code base hasn't changed for a long time - so please let me know is all okay.
There is a cosmestic issue here though with the info about Generate Cameras being present; this to should be hidden until button appears after server login confirmed.

**Comment by smeee-again** [comment]
The first time I tried it, it didn't do anything.  I restarted the plugin and then it worked.

**Comment by Ghawken** [comment]
OK - thanks for update.
I'll check that it appropriately saves info, sometimes nature of Indigo config boxes is box needs to be closed to register changes.

**Comment by Ghawken** [comment]
Have looked it over - and was a bug - the server details were not saving unless config dialog closed.

Have updated and fixed cosmetic info showing when it shouldn't in new version 1.1.10
In Plugin Store

Thanks again.
